### ISSUE TITLE
Costs design

### ISSUE THREAD

**Issue by chielbl** [Euricom/euricom-gpt#20]
Design:
- Request cost
- Total cost for chat 
- total cost in month

![Request cost](https://github.com/Euricom/euricom-gpt/assets/45933520/c86f1549-ee74-4344-bc4a-1ccfc15ab1c0)
![Chat cost](https://github.com/Euricom/euricom-gpt/assets/45933520/fb3a11b8-b3a3-42d6-a0f9-178b0bec7016)

**Comment by cosemansp** [comment]
Sample



![Image](https://github.com/Euricom/euricom-gpt/assets/3651002/3e6dd3fd-cba3-47a2-b288-a27691af9760)
